alias: Arriving home
trigger:
  platform: state
  entity_id: group.residents
  from: 'not_home'
  to: 'home'
condition:
  condition: state
  entity_id: input_boolean.presence_detection
  state: 'on'
action:
  - service: homeassistant.turn_on
    entity_id: 
      - group.family_room_lights
      - switch.family_room_tree
  - event: my_presence_home
