version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:11
    volumes:
      - /opt/smarthome/postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER}"
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 1m
    restart: always

  hass:
    container_name: hass
    image: homeassistant/home-assistant:0.111.4
    volumes:
      - /opt/smarthome/homeassistant/:/config
      - /etc/localtime:/etc/localtime:ro
      - ${SSL_PATH}/:/etc/ssl/private:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/serial/by-id/usb-0658_0200-if00
    restart: always
    # Needed due to HomeKit; it doesn't work from a Docker network
    network_mode: host
    depends_on:
      - postgres

