version: '3.6'

services:
  postgres:
    container_name: postgres
    image: postgres:10
    volumes:
      - /opt/smarthome/postgres:/var/lib/postgres/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - PGDATA
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER}"
      interval: 15s
      timeout: 30s
      retries: 3
      start_period: 1m
    restart: always

  influxdb:
    container_name: influxdb
    image: influxdb
    volumes:
      - /opt/smarthome/influxdb:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8086:8086
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana
    user: '1000'
    volumes:
      - /opt/smarthome/grafana:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3000:3000
    depends_on:
      - influxdb
    restart: always

  hass:
    container_name: hass
    image: homeassistant/home-assistant:0.86.4
    volumes:
      - /opt/smarthome/homeassistant/:/config
      - /etc/localtime:/etc/localtime:ro
      - ${SSL_PATH}/:/etc/ssl/private:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/dev/serial/by-id/usb-0658_0200-if00
    restart: always
    # Needed due to HomeKit; it doesn't work from a Docker network
    network_mode: host
    depends_on:
      - influxdb
      - postgres

  appdaemon:
    container_name: appdaemon
    image: smkelly/appdaemon:3.0.2
    build:
      context: ~smkelly/src/appdaemon/
    volumes:
      - /opt/smarthome/appdaemon:/conf
      - ${SSL_PATH}:/certs:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5050:5050
    restart: always
    depends_on:
      - hass

#  nodered:
#    container_name: nodered
#    image: nodered/node-red-docker:v8
#    volumes:
#      - /opt/smarthome/nodered:/data
#      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - 1880:1880
#    restart: always
#    depends_on:
#      - hass
