homeassistant:
  name: Home
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: !secret hass_elevation
  unit_system: imperial
  time_zone: America/Chicago
  internal_url: !secret hass_internal_url
  external_url: !secret hass_external_url
  customize: !include conf/customized.yaml
  packages: !include_dir_named conf/packages/
  auth_providers: !include conf/auth_providers.yaml

alarm_control_panel: !include conf/alarm_control_panel.yaml
alexa:
automation: !include_dir_list conf/automations/
binary_sensor: !include_dir_list conf/binary_sensors/
circadian_lighting:
cloud: !include conf/cloud.yaml
config:
device_tracker: !include conf/device_tracker.yaml
discovery: !include conf/discovery.yaml
ffmpeg:
frontend: !include conf/frontend.yaml
group: !include_dir_named conf/groups/
history: !include conf/history.yaml
http: !include conf/http.yaml
homekit: !include conf/homekit.yaml
hue: !include conf/hue.yaml
ios:
input_boolean: !include_dir_named conf/input_booleans/
input_datetime: !include_dir_named conf/input_datetimes/
intent_script: !include_dir_named conf/intent_scripts/
logbook: !include conf/logbook.yaml
logger: !include conf/logger.yaml
lovelace: !include conf/lovelace.yaml
map:
media_player:
mobile_app:
notify: !include conf/notifiers.yaml
person:
recorder: !include conf/recorder.yaml
remote: !include conf/remote.yaml
scene: !include_dir_list conf/scenes/
script: !include_dir_named conf/scripts/
sensor: !include_dir_list conf/sensors/
stream:
sun:
system_health:
tts: !include conf/tts.yaml
twilio: !include conf/twilio.yaml
updater:
zeroconf:
zone: !include conf/zones.yaml
