alias: Wake Up Lights
trigger:
  platform: time
  seconds: 0
condition:
  - condition: state
    entity_id: input_boolean.wakeup_lights
    state: 'on'
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  - condition: template
    value_template: >
      {% set ts = states.input_datetime.alarm_time.attributes.timestamp - 600 %}
      {% set midnight = as_timestamp("%d-%d-%d 00:00:00" | format(now().year, now().month, now().day)) %}
      {{ now().strftime("%H:%M") == (midnight + ts) | timestamp_custom("%02H:%02M", 1) }}
action:
  service: script.turn_on
  entity_id: script.wakeup
