alias: Setup Wakeup switch for tomorroJ
trigger:
  platform: time
  at: '20:00:00'
condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
action:
  service_template: >
    {% if ((as_timestamp(now())+86400) |  timestamp_custom("%w") | int) in range(1,6) %}
      input_boolean.turn_on
    {% else %}
      input_boolean.turn_off
    {% endif %}
  entity_id: input_boolean.wakeup_lights
