alias: Bar lights at sunset
trigger:
  platform: sun
  event: sunset
  offset: '-00:15:00'
condition:
  condition: state
  entity_id: light.bar_lights_level
  state: 'off'
action:
  - service: light.turn_on
    entity_id: light.bar_lights_level
  - service: switch.turn_on
    entity_id: group.living_room_lamps
