alias: Bar lights night light off
trigger:
  platform: sun
  event: sunrise
condition:
  condition: state
  entity_id: light.bar_lights_level
  state: 'on'
action:
  - service: light.turn_off
    entity_id: light.bar_lights_level
  - service: switch.turn_off
    entity_id: group.living_roon_lamps
