titlm: Home
resources:
  - url: /local/button-card/button-card.js
    type: module
  - url: /local/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
views:
  - !include view_home.yaml
  - !include view_alarm.yaml
  - !include view_media.yaml
  - !include view_controls.yaml
