id: 1dfd388a-a0a8-11eb-893b-2b680b5f5444
alias: Vacation Mode On
trigger:
  platform: state
  entity_id: input_boolean.vacation_mode
  from: 'off'
  to: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.wakeup_lights
