id: 165890c0-a0a8-11eb-b574-63f3dbf35a84
alias: Vacation Mode Off
trigger:
  platform: state
  entity_id: input_boolean.vacation_mode
  from: 'on'
  to: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.wakeup_lights
