alias: Vacation Mode On
trigger:
  platform: state
  entity_id: input_boolean.vacation_mode
  from: 'off'
  to: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.wakeup_lights
