alias: 'Front Door light off in morning'
trigger:
  platform: sun
  event: sunrise
  offset: '+00:15:00'
action:
  - service: light.turn_off
    entity_id: light.front_door_1
  - service: light.turn_off
    entity_id: light.front_door_2

