id: 9fb565ec-a0a7-11eb-b393-a30087cd7157
alias: Login Failure
trigger:
  platform: template
  value_template: "{{ states('persistent_notification.httplogin') != 'unknown' }}"
action:
  service: notify.smkelly_sms
  data:
    message: "HASS bad login attempt."
