alias: Start HomeKit
initial_state: "on"
trigger:
  - platform: event
    event_type: zwave.network_ready
  - platform: event
    event_type: zwave.network_complete
action:
  - service: homekit.start
  # We only want to fire this once per startup
  - service: automation.turn_off
    entity_id: automation.start_hass
