alias: Start HomeKit
initial_state: "on"
trigger:
  - platform: event
    event_type: zwave.network_ready
  - platform: event
    event_type: zwave.network_complete
action:
  - service: homekit.start
  - service: notify.ios_smkelly
    data:
      message: "HomeKit starting."
