id: b9925664-a0a7-11eb-aea4-5f7992db09d1
alias: 'Update Available Notification'
trigger:
  platform: state
  entity_id: binary_sensor.updater
  from: "off"
  to: "on"
action:
  service: notify.ios_smkelly
  data:
    message: 'Update for Home Assistant is available.'

