- platform: unifi
  host: !secret unifi_host
  username: !secret unifi_username
  password: !secret unifi_password
  verify_ssl: false
  monitored_conditions:
    - ap_mac
    - assoc_time
    - channel
    - first_seen
    - ip
    - last_seen
    - vlan
  new_device_defaults:
    track_new_devices: false

- platform: snmp
  host: !secret gateway_ip
  community: !secret gateway_snmp_community
  baseoid: !secret gateway_mac_oid
  new_device_defaults:
    track_new_devices: false
