# For reasons I don't understand, the binary sensor that comes directly from Z-wave
# doesn't actually ever change on motion. If anybody else has a HS-FLS100+, I'd be
# interested in your experience here.
binary_sensor:
  - platform: template
    sensors:
      backyard_motion:
        friendly_name: "Backyard Motion"
        device_class: motion
        value_template: "{{ states('sensor.backyard_floodlight_burglar')|int == 8 }}"
