# Control the dehumidifier in the master bathroom.
#
# * Turn it on when sleeping ends.
# * Turn it off when sleeping starts.
# * Turn it on at 10AM if it isn't already on.

automation:
  - id: b1d73f2e-a06c-11eb-8305-63c34ebd06ff
    alias: "Bathroom Dehumidifier: Turn on"
    trigger:
      - id: "wakeup"
        platform: state
        entity_id: input_boolean.sleeping
        to: "off"
      - id: "fallback"
        platform: time
        at: "08:00:00"
    condition:
      condition: state
      entity_id: switch.bathroom_dehumidifier
      state: "off"
    action:
      service: switch.turn_on
      entity_id: switch.bathroom_dehumidifier

  - id: cac4f4cc-a06c-11eb-a01b-fbddd8111840
    alias: "Bathroom Dehumidifier: Bed time and turn off"
    trigger:
      platform: state
      entity_id: input_boolean.sleeping
      to: "on"
    condition:
      condition: state
      entity_id: switch.bathroom_dehumidifier
      state: "on"
    action:
      service: switch.turn_off
      entity_id: switch.bathroom_dehumidifier
