automation:
  - alias: "Dark Mode: On"
    trigger:
      - platform: sun
        event: sunset
      - platform: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        above: 80
      - platform: numeric_state
        entity_id: sensor.dark_sky_precip_probability_0h
        above: 50
    condition:
      condition: and
      conditions:
        # dark_mode is off AND (Sun is set OR (cloudy AND likely to rain))
        - condition: state
          entity_id: input_boolean.dark_mode
          state: "off"
        - condition: or
          conditions:
          - condition: sun
            after: sunset
          - condition: and
            # IF it is cloudy AND a good chance of rain
            conditions:
            - condition: numeric_state
              entity_id: sensor.dark_sky_cloud_coverage
              above: 80
            - condition: numeric_state
              entity_id: sensor.dark_sky_precip_probability_0h
              above: 50
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.dark_mode

  - alias: "Dark Mode:: Off"
    trigger:
      - platform: sun
        event: sunrise
      - platform: numeric_state
        entity_id: sensor.dark_sky_cloud_coverage
        below: 70
      - platform: numeric_state
        entity_id: sensor.dark_sky_precip_probability_0h
        below: 40
    condition:
      - condition: state
        entity_id: input_boolean.dark_mode
        state: "on"
      - condition: sun
        after: sunrise
      - condition: sun
        before: sunset
      - condition: or
        conditions:
          - condition: numeric_state
            entity_id: sensor.dark_sky_cloud_coverage
            below: 70
          - condition: numeric_state
            entity_id: sensor.dark_sky_precip_probability_0h
            below: 40
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.dark_mode

input_boolean:
  dark_mode:
    name: Dark Mode

