automation:
  - id: 181aee54-a0a7-11eb-a126-d36130d6693d
    alias: "Dark Mode: On"
    trigger:
      - platform: sun
        event: sunset
      - platform: numeric_state
        entity_id: sensor.backyard_floodlight_illuminance
        below: 100
    condition:
        - condition: state
          entity_id: input_boolean.dark_mode
          state: "off"
        - condition: or
          conditions:
          - condition: sun
            after: sunset
          - condition: numeric_state
            entity_id: sensor.backyard_floodlight_illuminance
            below: 100
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.dark_mode

  - id: 21cd43f2-a0a7-11eb-9586-ef4748dec016
    alias: "Dark Mode:: Off"
    trigger:
      - platform: sun
        event: sunrise
      - platform: numeric_state
        entity_id: sensor.backyard_floodlight_illuminance
        above: 100
    condition:
      - condition: state
        entity_id: input_boolean.dark_mode
        state: "on"
      - condition: sun
        after: sunrise
      - condition: sun
        before: sunset
      - condition: numeric_state
        entity_id: sensor.backyard_floodlight_illuminance
        above: 100
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.dark_mode

input_boolean:
  dark_mode:
    name: Dark Mode
    