automation:
  - alias: "Dark Mode: On"
    trigger:
      - platform: sun
        event: sunset
      - platform: numeric_state
        entity_id: sensor.backyard_floodlight_luminance
        below: 100
    condition:
      condition: and
      conditions:
        # dark_mode is off AND (Sun is set OR (cloudy AND likely to rain))
        - condition: state
          entity_id: input_boolean.dark_mode
          state: "off"
        - condition: or
          conditions:
          - condition: sun
            after: sunset
          - condition: numeric_state
            entity_id: sensor.backyard_floodlight_luminance
            below: 100
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.dark_mode

  - alias: "Dark Mode:: Off"
    trigger:
      - platform: sun
        event: sunrise
      - platform: numeric_state
        entity_id: sensor.backyard_floodlight_luminance
        above: 100
    condition:
      - condition: state
        entity_id: input_boolean.dark_mode
        state: "on"
      - condition: sun
        after: sunrise
      - condition: sun
        before: sunset
      - condition: numeric_state
        entity_id: sensor.backyard_floodlight_luminance
        above: 100
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.dark_mode

input_boolean:
  dark_mode:
    name: Dark Mode
    