adaptive_lighting:
  name: "Family Room Light Adjuster"
  min_color_temp: 2500
  min_brightness: 75
  lights:
    - light.family_room_lights

automation:
  - id: aa4f346a-9f21-11eb-aac3-af83f59742a4
    alias: 'Random Family Room color'
    trigger:
      platform: time_pattern
      seconds: 0
    condition:
      condition: state
      entity_id: input_boolean.rainbow_mode
      state: 'on'
    action:
      service: light.turn_on
      entity_id: light.family_room_lights
      data:
        effect: random
        transition: 60
        brightness: 255

  - id: d43826a4-a072-11eb-86bb-6731703e492c
    alias: "Reset from random colors in Family Room"
    trigger:
      platform: state
      entity_id: input_boolean.rainbow_mode
      from: 'on'
      to: 'off'
    action:
      service: adaptive_lighting.apply
      data:
        entity_id: switch.adaptive_lighting_family_room_light_adjuster
        lights:
          - light.family_room_1
          - light.family_room_2
          - light.family_room_3
          - light.family_room_4

input_boolean:
  rainbow_mode:
    name: Rainbow Mode

light:
  - platform: group
    unique_id: "f35f2291-591f-4eca-89ac-71a33474540b"
    name: "Family Room Lights"
    entities:
      - light.family_room_1
      - light.family_room_2
      - light.family_room_3
      - light.family_room_4