automation:
  - id: a88d986e-aa21-11eb-98e7-378228718138
    alias: "Front Door motion"
    mode: restart
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_motion
        from: "off"
        to: "on"
    condition:
      condition: state
      entity_id: input_boolean.dark_mode
      state: "on"

    action:
      - service: switch.turn_on
        entity_id: switch.entryway_light
      - wait_for_trigger:
          platform: state
          entity_id: binary_sensor.front_door_motion
          from: "on"
          to: "off"
          for: "0:02:00"
      - service: switch.turn_off
        entity_id: switch.entryway_light

  - id: 267061ee-a06d-11eb-9941-4fecaf9adbd9
    alias: 'Dark mode: Front Door light off'
    trigger:
      platform: state
      entity_id: input_boolean.dark_mode
      to: "off"
    action:
      - service: light.turn_off
        entity_id:
          - light.front_door_1
          - light.front_door_2

  - id: 316af672-a06d-11eb-b4d0-5f9ca836271c
    alias: 'Dark mode: Front Door light on'
    trigger:
      platform: state
      entity_id: input_boolean.dark_mode
      to: "on"
    action:
      service: scene.turn_on
      data:
        entity_id: >
          {% macro easter(year) %}
            {% set a = year % 19 %}
            {% set b = year // 100 %}
            {% set c = year % 100 %}
            {% set d = ((19 * a + b - b // 4 - ((b - (b + 8) // 25 + 1) // 3) + 15) % 30) %}
            {% set e = (32 + 2 * (b % 4) + 2 * (c // 4) - d - (c % 4)) % 7 %}
            {% set f = d + e - 7 * ((a + 11 * d + 22 * e) // 451) + 114 %}
            {{ "%d%02d" % (f // 31, f % 31 + 1) }}
          {% endmacro %}

          {% set day = "%d%02d" % (now().month, now().day) %}
          {% set year = now().year %}

          {% if day|int in (1231, 101) %}
            {% set scn = "newyear" %}
          {% elif day|int in range(207, 215) %}
            {% set scn = "valentine" %}
          {% elif day|int in range(315, 320) %}
            {% set scn = "stpats" %}
          {% elif day|int in range(easter(year)|int - 4, easter(year)|int + 5) %}
            {% set scn = "easter" %}
          {% elif day|int == 614 or day|int in range(0701, 0706) %}
            {% set scn = "flag" %}
          {% elif day|int in range(1024, 1032) %}
            {% set scn = "halloween" %}
          {% elif day|int in range(1129, 1231) %}
            {% set scn = "christmas" %}
          {% else %}
            {% set scn = "normal" %}
          {% endif %}
          {% set scn = "scene.front_door_" + scn %}

          {# In case I've not made it yet... #}
          {% if is_state(scn, "scening") %}
            {{ scn }}
          {% else %}
            scene.front_door_normal
          {% endif %}
