automation:
  - alias: "Living Room lights: Dark Mode (off)"
    trigger:
      platform: state
      entity_id: input_boolean.dark_mode
      to: "off"
    condition:
      condition: state
      entity_id: light.bar_lights_level
      state: 'on'
    action:
      - service: light.turn_off
        entity_id: light.bar_lights_level
      - service: switch.turn_off
        entity_id: group.living_room_lamps

  - alias: "Living Room lights: Dark Mode (on)"
    trigger:
      platform: state
      entity_id: input_boolean.dark_mode
      to: "on"
    condition:
      condition: state
      entity_id: light.bar_lights_level
      state: 'off'
    action:
      - service: light.turn_on
        entity_id: light.bar_lights_level
      - service: switch.turn_on
        entity_id: group.living_room_lamps

  - alias: "Living Room lamps off timer"
    trigger:
      platform: time
      at: "23:00:00"
    condition:
      condition: state
      entity_id: group.living_room_lamps
      state: "on"
    action:
      - delay:
          seconds: "{{ range(0, 7200) | random | int }}"
      - service: homeassistant.turn_off
        entity_id: group.living_room_lamps
