automation:
  - id: 262a286f-f0bd-4248-bd3b-986c0591a418
    alias: "Turn off sleep via dehumidifier"
    trigger:
      platform: state
      entity_id: switch.bathroom_dehumidifier
      to: "on"
    condition:
      condition: state
      entity_id: input_boolean.sleeping
      state: 'on'
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.sleeping

  - id: a0987c68-a06d-11eb-a024-6382b11f8bde
    alias: "Dark mode: Master Bedroom on"
    trigger:
      platform: state
      entity_id: input_boolean.dark_mode
      to: "on"
    condition:
      condition: state
      entity_id: light.master_hall
      state: 'off'
    action:
      service: light.turn_on
      entity_id: light.master_hall
      data:
        brightness: 255
        kelvin: 2700

  - id: a09881e0-a06d-11eb-a025-4f4f5a1383e6
    alias: "Dark mode: Master Bedroom off"
    trigger:
      platform: state
      entity_id: input_boolean.dark_mode
      to: "off"
    condition:
      condition: state
      entity_id: light.master_hall
      state: 'on'
    action:
      service: light.turn_off
      entity_id: light.master_hall

  - id: a0988370-a06d-11eb-a026-3bda04edafa9
    alias: "Turn off bedroom lights for TV (Sonos)"
    trigger:
      platform: state
      entity_id: media_player.master_bedroom
      to: "playing"
    condition:
      condition: time
      after: "21:00:00"
    action:
      - service: scene.turn_on
        entity_id:
          - scene.sleep_time
          - scene.sleep_time_bedroom
        data:
          transition: 5

adaptive_lighting:
  name: "Master Bedroom Light Adjuster"
  lights:
    - light.master_1
    - light.master_2
    - light.master_3
    - light.master_4
    - light.master_hall
