automation:
  - alias: "Dark mode: Master Bedroom on"
    trigger:
      platform: state
      entity_id: input_boolean.dark_mode
      to: "on"
    condition:
      condition: state
      entity_id: light.master_hall
      state: 'off'
    action:
      service: light.turn_on
      entity_id: light.master_hall
      data:
        brightness: 255
        kelvin: 2700

  - alias: "Dark mode: Master Bedroom off"
    trigger:
      platform: state
      entity_id: input_boolean.dark_mode
      to: "off"
    condition:
      condition: state
      entity_id: light.master_hall
      state: 'on'
    action:
      service: light.turn_off
      entity_id: light.master_hall

  - alias: "Turn off bedroom lights for Apple TV"
    trigger:
      platform: state
      entity_id: media_player.master_bedroom_appletv
      to: "playing"
    condition:
      condition: time
      after: "21:30:00"
    action:
      - service: light.turn_off
        entity_id: group.master_bedroom
