automation:
  - id: 7f7dfc4e-a0a7-11eb-bd3f-2742a472f21f
    alias: Trash Day Reminder
    trigger:
      platform: time
      at: '19:30:00'
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: time
        weekday:
          - sun
          - wed
    action:
      service: notify.all_sms
      data:
        message: "Reminder: Tomorrow is trash day."

  - id: 882f2728-a0a7-11eb-bf73-af497201a3d9
    alias: Recycle Day Reminder
    trigger:
      platform: time
      at: '19:30:00'
    condition:
      - condition: state
        entity_id: input_boolean.vacation_mode
        state: 'off'
      - condition: time
        weekday:
          - tue
    action:
      service: notify.all_sms
      data:
        message: "Reminder: Tomorrow is recycling day."

